<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>com.team20</groupId>
    <artifactId>text-editor-parent</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <relativePath>../../pom.xml</relativePath>
  </parent>

  <artifactId>plugins-spellcheck-simple</artifactId>
  <name>plugins-spellcheck-simple</name>
  <packaging>jar</packaging>
  <description>Simple spell checking adapter and command</description>

  <dependencies>
    <dependency>
      <groupId>com.team20</groupId>
      <artifactId>text-editor</artifactId>
      <version>${project.parent.version}</version>
    </dependency>
  </dependencies>
</project>